/**
 * System Constants
 */

const ROLES = Object.freeze({
  DRIVER: 'DRIVER',
  PROVIDER: 'PROVIDER',
  ADMIN: 'ADMIN'
});

const USER_STATUS = Object.freeze({
  ACTIVE: 'ACTIVE',
  BLOCKED: 'BLOCKED',
  PENDING_APPROVAL: 'PENDING_APPROVAL',
  UNDER_REVIEW: 'UNDER_REVIEW',
  REJECTED: 'REJECTED',
  SUSPENDED: 'SUSPENDED'
});

const BOOKING_STATUS = Object.freeze({
  PENDING: 'Pending',
  CONFIRMED: 'Confirmed',
  ACTIVE: 'Active',
  COMPLETED: 'Completed',
  CANCELLED: 'Cancelled',
  EXPIRED: 'Expired',
  ENTERING: 'ENTERING',
  PARKED: 'PARKED',
  EXITING: 'EXITING'
});

const VEHICLE_CATEGORIES = Object.freeze([
  'Bike', 'Scooter', 'Sedan', 'Hatchback', 'SUV',
  'Luxury Car', 'EV', 'Mini Truck', 'Truck', 'Bus', 'Handicap'
]);

const SOCKET_EVENTS = Object.freeze({
  ZONE_UPDATED: 'ZONE_UPDATED',
  SLOT_FREED: 'SLOT_FREED',
  SLOT_OCCUPIED: 'SLOT_OCCUPIED',
  NEW_NOTIFICATION: 'NEW_NOTIFICATION',
  VEHICLE_STATUS_UPDATE: 'VEHICLE_STATUS_UPDATE',
  BOOKING_CANCELLED: 'BOOKING_CANCELLED',
  QUEUE_OFFERED: 'QUEUE_OFFERED',
  QUEUE_STATUS_UPDATED: 'QUEUE_STATUS_UPDATED',
  QUEUE_STATE_CHANGED: 'QUEUE_STATE_CHANGED',
  PROVIDER_DEVICE_UPDATED: 'PROVIDER_DEVICE_UPDATED',
  ADMIN_DEVICE_UPDATED: 'ADMIN_DEVICE_UPDATED',
  DEVICE_OFFLINE: 'DEVICE_OFFLINE'
});

module.exports = {
  ROLES,
  USER_STATUS,
  BOOKING_STATUS,
  VEHICLE_CATEGORIES,
  SOCKET_EVENTS
};
